    <div class="ttlsup">API de Productos con PHP</div>
    <div class="container">
        <div class="row">
            <div class="caja">
                <div class="col-lg-12 text-center ppalc">
                    
                    <hr class="visible-xs"/>
                </div>
                <div class="col-lg-12 text-center">
                    <h2>
                        <small>
                            <strong class='Eslog'>Trabajos</strong>
                        </small>
                    </h2>
                    <hr class="visible-xs"/>
                    
                    <h2 class="intro-text text-center">&nbsp;</h2>
                    <div class="imgGrnd"><img src="" class="imgGrnd"></div>
                </div>
            </div>
        </div>
    </div>