<div class="ttlsup">Activación de Usuario</div>
<div class="container">
    <div class="row">
        <div class="caja">
            <div class="col-lg-12 text-center ppalc">
                <h2>Su cuenta ha sido activada</h2>
                <p></p>
                <h4><a href='<?php echo BASE_URL; ?>'>Ir al inicio</a></h4><br>
                <?php
                if (!Session::get('autenticado')) {
                    echo "| <h4><a href='login'>Iniciar Sesión</a></h4>";
                }
                ?>
            </div>
        </div>
    </div>
</div>